// Country names from CNB, keyed by currency code
export const COUNTRY_MAP: Record<string, string> = {
  AUD: 'Australia',
  BRL: 'Brazil',
  CAD: 'Canada',
  CNY: 'China',
  DKK: 'Denmark',
  EUR: 'EMU',
  HKD: 'Hongkong',
  HUF: 'Hungary',
  ISK: 'Iceland',
  XDR: 'IMF',
  INR: 'India',
  IDR: 'Indonesia',
  ILS: 'Israel',
  JPY: 'Japan',
  MYR: 'Malaysia',
  MXN: 'Mexico',
  NZD: 'New Zealand',
  NOK: 'Norway',
  PHP: 'Philippines',
  PLN: 'Poland',
  RON: 'Romania',
  SGD: 'Singapore',
  ZAR: 'South Africa',
  KRW: 'South Korea',
  SEK: 'Sweden',
  CHF: 'Switzerland',
  THB: 'Thailand',
  TRY: 'Turkey',
  GBP: 'United Kingdom',
  USD: 'USA',
};
